Ft sdk bitmovin integration
sambatech/player_sdk_ios pull request #93
Opened 2020-09-08 18:55 UTC by luishenkoti

## O que está sendo entregue
Integração do SDK com o analytics do Bitmovin

## Pontos de atenção
n/a

## Quick Sanity Test
Fazer o build do SDK e atualizar a dependência em algum projeto que já use o SambaPlayer, executar o app, tocar um vídeo e verificar os registros no painel do analytics do Bitmovin.

## Evidências de Funcionamento
**bundleId**: br.com.joinkids (sambaplay)
**ph**: e5d297df7cc95318f514c3a27be7e4cb
**m**: 99db0952cbb4615a09a3e406f6b86c4f

**loaded**
![image](https://user-images.githubusercontent.com/45015382/92515966-d9fb7c80-f1ea-11ea-91ac-ada95d5df9c7.png)

2020-09-16 13:39 UTC, adrianotk commented on SambaPlayer/SambaPlayer.swift
> +//    private var avPlayer: AVPlayer?
@luishenkoti , tem algum motivo para esse código comentado estar aqui? Caso não tenha, peço a gentileza de removê-lo.

2020-09-16 13:42 UTC, adrianotk requested changes
@luishenkoti ,

O arquivo SambaPlayer.xcodeproj/project.pbxproj está com conflitos. Favor resolvê-los.

2020-10-06 21:39 UTC, luishenkoti commented on SambaPlayer/SambaPlayer.swift
> +//    private var avPlayer: AVPlayer?
removido

2020-11-09 13:09 UTC, adrianotk approved these changes

2020-11-09 13:09 UTC, merged